apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: deliverable-to-run-cluster-reconciler
  namespace: default
spec:
  fetch:
  - git:
      url: https://github.com/Mpluya/unicorn-run-qa-deliverable
      ref: origin/main
  syncPeriod: 1m0s
  cluster:
    # specifies namespace in destination cluster (optional)
    namespace: default
    # specifies secret containing kubeconfig (required)
    kubeconfigSecretRef:
      # specifies secret name within app's namespace (required)
      name: kubeconfig-deliverable-reconciler-secret
      # specifies key that contains kubeconfig (optional)
      key: value
  deploy:
  - kapp: {}
  template:
  - ytt: {}
  - kbld: {}