#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-secret
data:
  id_rsa: #@ data.values.git_writer.base64_encoded_ssh_key
  known_hosts: #@ data.values.git_writer.base64_encoded_known_hosts