#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: code-analysis
  namespace: default
  labels:
    workload-intent: code-analysis
spec:
  serviceAccountName: #@ data.values.service_account_name
  params:
    - name: git_server
      value: github.com
    - name: git_repository
      value: Mpluya/code-analysis-config
    - name: git_branch
      value: main 
  source:
    git:
      ref:
        branch: main
      url: ssh://git@github.com/Mpluya/code-analysis
          