apiVersion: v1
items:
- apiVersion: scanning.apps.tanzu.vmware.com/v1beta1
  kind: ScanPolicy
  metadata:
    name: sample-scan-policy
    namespace: default
  spec:
    regoFile: |
      package policies

      default isCompliant = false

      # Accepted Values: "Critical", "High", "Medium", "Low", "Negligible", "UnknownSeverity"
      violatingSeverities := ["Critical","High","UnknownSeverity"]
      ignoreCVEs := ["CVE-2019-8457", "CVE-2019-5018", "CVE-2020-11655", "CVE-2020-11656", "CVE-2020-13630", "CVE-2019-19646", "CVE-2021-42378","CVE-2021-42379","CVE-2021-42380", "CVE-2021-42381","CVE-2021-42382", "CVE-2021-42384","CVE-2021-42385","CVE-2021-42386"]

      contains(array, elem) = true {
        array[_] = elem
      } else = false { true }

      isSafe(match) {
        fails := contains(violatingSeverities, match.Ratings.Rating[_].Severity)
        not fails
      }

      isSafe(match) {
        ignore := contains(ignoreCVEs, match.Id)
        ignore
      }

      isCompliant = isSafe(input.currentVulnerability)
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""