#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
---
apiVersion: v1
kind: Secret
metadata:
  name: scanner-reg-cred
type: kubernetes.io/dockerconfigjson
stringData:
  #@ registry_creds = {"username": data.values.tanzu_registry.username, "password": data.values.tanzu_registry.password}
  .dockerconfigjson: #@ json.encode({"auths": {data.values.tanzu_registry.server: registry_creds}})