#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: code-analysis
spec:
  urlPath: .status.outputs.url
  revisionPath: .status.outputs.revision

  template:
    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: $(workload.metadata.name)$
    spec:
      serviceAccountName: #@ data.values.service_account_name
      runTemplateRef:
        name: tekton-sonar-taskrun

      selector:
        resource:
          apiVersion: tekton.dev/v1beta1
          kind: Task
        matchingLabels:
          task: code-analysis

      inputs:
        source-url: $(sources.source.url)$
        source-revision: $(sources.source.revision)$
