#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: code-analysis
  namespace: default
  labels:
    app.kubernetes.io/part-of: code-analysis
    workload-intent: code-analysis
spec:
  serviceAccountName: #@ data.values.service_account_name
  params:
    - name: gitops_server
      value: github.com
    - name: gitops_repository
      value: Mpluya/code-analysis-config
    - name: gitops_branch
      value: main 
  source:
    git:
      ref:
        branch: main
      url: ssh://git@github.com/Mpluya/code-analysis
          