apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: code-analysis
  namespace: default
  labels:
    workload-intent: code-analysis
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/Mpluya/outer-loop