#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: delivery-with-code-promotion
spec:
  params:
  - name: deliverable_repository_owner
    default: Mpluya
  - name: deliverable_repository_name
    default: config-deliverable-prod
  selector:
    app.tanzu.vmware.com/deliverable-type: web
    deliverable-intent: code-promotion
  resources:
  - name: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: delivery-source-template
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git

  - name: deployer
    templateRef:
      kind: ClusterDeploymentTemplate
      name: app-deploy
    params:
      - name: serviceAccount
        value: default
    deployment:
      resource: source-provider

  - configs:
    name: prod-deliverable-config
    sources:
    - name: source
      resource: source-provider
    templateRef:
      kind: ClusterConfigTemplate
      name: config-deliverable-template

  - name: prod-deliverable-config-writer-and-pr
    configs:
    - name: config
      resource: prod-deliverable-config
    sources:
    - name: source
      resource: source-provider
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterTemplate
      name: deliverable-config-writer-and-pr-template