---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: image-prebuilt-supply-chain
spec:
  selector:
    workload-intent: image-prebuilt
  resources:
    - name: image-provider
      templateRef:
        kind: ClusterImageTemplate
        name: prebuilt-image

    - name: image-scanner
      templateRef:
        kind: ClusterImageTemplate
        name: image
      images:
        - resource: image-provider
          name: prebuilt-image
  
    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: app-deploy
      images:
        - resource: image-scanner
          name: image

    - name: config-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: app-config
      images:
        - resource: image-scanner
          name: image

    # writes config from app-config to be pushed as a bundle by imgpkg
    - name: image-writer
      templateRef:
        kind: ClusterTemplate
        name: image-writer
      configs:
        - resource: config-provider 
          name: app-config

    - name: deliverable
      templateRef:
        kind: ClusterTemplate
        name: deliverable-tpl