#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterConfigTemplate
metadata:
  name: app-config
spec:
  configPath: .data
  params:
  - name: registry_server
    default: ""
  - name: registry_repository
    default: ""

  ytt: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:yaml", "yaml")
    
    #@ def image():
    #@   return "/".join([
    #@    data.values.params.registry_server,
    #@    data.values.params.registry_repository,
    #@    "-".join([
    #@      data.values.workload.metadata.name,
    #@      data.values.workload.metadata.namespace,
    #@      "bundle",
    #@    ])
    #@   ]) + ":" + data.values.workload.metadata.uid
    #@ end

    #@ def delivery():
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations: 
        kapp.k14s.io/disable-default-label-scoping-rules: ''
        kapp.k14s.io/disable-default-ownership-label-rules: ''
      name: #@ data.values.workload.metadata.name
    spec:
      serviceAccountName: #@ data.values.workload.spec.serviceAccountName
      selector:
        matchLabels:
          app: #@ data.values.workload.metadata.name
      template:
        metadata:
          labels:
            app: #@ data.values.workload.metadata.name
        spec:
          containers:
            - name: main
              image: #@ image()
    #@ end

    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: #@ data.values.workload.metadata.name
    data:
      delivery.yml: #@ yaml.encode(delivery())
        