apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: deliverable-image-source
spec:
  imagePath: .spec.image

  template:
    apiVersion: source.apps.tanzu.vmware.com/v1alpha1
    kind: ImageRepository
    metadata:
      name: $(deliverable.metadata.name)$-app
    spec:
      serviceAccount: $(deliverable.spec.serviceAccountName)$
      interval: 1m0s
      image: $(deliverable.spec.source.image)$