apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: tekton-sonar-taskrun
spec:
  outputs:
    url: spec.params[?(@.name=="source-url")].value
  template:
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: $(runnable.metadata.name)$-
      labels: $(runnable.metadata.labels)$
    spec:
      params:
      - name: source-url
        value: $(runnable.spec.inputs.source-url)$
      - name: source-revision
        value: $(runnable.spec.inputs.source-revision)$
      taskRef:
        name: sonar