apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    apps.tanzu.vmware.com/task: test
  name: sonar
  namespace: default
spec:
  params:
  - name: source-url
  - name: source-revision
  steps:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/gradle
    name: code-analysis
    resources: {}
    script: |-
      cd `mktemp -d`

      wget -qO- $(params.source-url) | tar xvz
      chmod +x mvnw
      ./mvnw verify sonar:sonar